### ISSUE TITLE
Dead endpoint

### ISSUE THREAD

**Issue by FliiFe** [konnectors/sfr#236]
This konnector attempts to grab a token using the following endpoint:

`https://www.sfr.fr/cas/services/rest/1.0/createToken.json?duration=8640`

As far as I can tell, this endpoint does not exist anymore, as it always responds with
```html
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 17733431862587649576<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
```
with no significant header.

**Comment by maelgangloff** [comment]
I think the correct address is `https://www.sfr.fr/cas/services/rest/3.2/createToken.json?duration=86400`
